[package]
name = "scoped-gc-derive"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]

[lib]
name = "scoped_gc_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "^0.2.3"
quote = "^0.4.2"
syn = "^0.12.14"
synstructure = "^0.7.0"
